# Generated by Django 2.1.8 on 2019-04-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
